export enum QueryParams {
  REL_ABS_FILTER = 'rel',
  TIME_FILTER = 'time',
  GEO_FILTER = 'geo',
  CUMULATIVE_FILTER = 'sum',
  REGIONS_FILTER = 'regions',
  OCCUPANCY_FILTER = 'occ',
  GEO_VIEW_FILTER = 'geoView',
  TEST_POS_VIEW_FILTER = 'testPosView',
  DEMO_VIEW_FILTER = 'demoView',
  DEMO_VIEW_AGE_RANGE_FILTER = 'ageRanges',
  DEMO_CUMULATIVE_FILTER = 'demoSum',
  AGE_GROUP_CLASSIFICATION_FILTER = 'ageGroupClass',
  DEMO_AGE_FILTER = 'demoAge',
  GEO_AGE_FILTER = 'geoAge',
  DEMO_SEX_FILTER = 'demoGender',
  INDICATOR = 'indicator',
  INDICATION_CUMULATIVE_FILTER = 'indSum',
  LOCATION_CUMULATIVE_FILTER = 'locSum',
  GRP_RATIO_CUMULATIVE_FILTER = 'grpRatioSum',
  VACCINE_CUMULATIVE_FILTER = 'vaccineSum',
  VACC_DOSES_CUMULATIVE_TYPE_FILTER = 'vaccDosesCumulType',
  GRP_RANGE = 'grpRange',
  VARIANT_FILTER = 'variants',
  LOCATION_VIEW_LOCATION_FILTER = 'locations',
  INDICATION_VIEW_INDICATION_FILTER = 'indications',
  VACCINE_VIEW_VACCINE_FILTER = 'vaccines',
  VACC_SYMPTOMS_VACCINE_FILTER = 'vaccine',
  VACC_SYMPTOMS_DEMO_AGE_RANGE_FILTER = 'ageRangesSymptoms',
  DEV_CUMULATIVE_FILTER = 'devSum',
  VACC_PERSONS_DEV_CUMULATIVE_FILTER = 'vaccPersonsDevSum',
  ISO_WEEK_FILTER = 'isoWeek',
  GEO_DATE = 'geoDate',
  VACC_REL_FILTER = 'vaccRel',
  VACC_PERSONS_REL_FILTER = 'vaccPersonsRel',
  MAP_ZOOM_FILTER = 'mapZoom',
  DEVELOPMENT_VIEW_FILTER = 'devView',
  DEVELOPMENT_VIEW_TOTAL_FILTER = 'devViewTotal',
  VACC_STATUS_DEV_REL_FILTER = 'vaccStatusDevRel',
  VACC_STATUS_VACCINE_DEV_CUMULATIVE_FILTER = 'vaccStatusVaccSum',
  VACC_STATUS_DEMO_REL_FILTER = 'vaccStatusDemoRel',
  VACC_STATUS_DEMO_AGE_RANGE = 'vaccStatusAgeRange',
  VACC_STATUS_VACCINE = 'vaccineStatus',

  GDI_OBJECT = 'gdiObject',

  SHOW_I18N_KEYS = 'showI18nKeys',
  FORCE_DATA_STATE = 'forceDataState',

  IS_EXPORT = 'isExport',
  HIDE_INFO = 'hideInfo',
}
